services:
  hpo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./hp.obo:/data/hp.obo:ro
      - ./hp-base.owl:/data/hp.owl:ro
    environment:
      - HPO_OBO_PATH=/data/hp.obo
      - HPO_OWL_PATH=/data/hp.owl
    profiles:
      - python

  hpo-api-node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8000:8000"
    volumes:
      - ./hp.obo:/data/hp.obo:ro
    environment:
      - HPO_OBO_PATH=/data/hp.obo
    profiles:
      - node
